.authenticate-to-package-registry:
  - &authenticate-to-package-registry |
    echo "$NPM_SCOPE:registry=https://$NPM_REGISTRY_HOST_PATH" >> ~/.npmrc
    echo "//$NPM_REGISTRY_HOST_PATH:_authToken=$NPM_WRITE_TOKEN" >> ~/.npmrc
    echo "//$NPM_PROJECT_HOST_PATH_PREFIX$CI_PROJECT_ID$NPM_PROJECT_HOST_PATH_SUFFIX:_authToken=$NPM_WRITE_TOKEN" >> ~/.npmrc

before_script:
  - node --version
  - npm --version

stages:
  - build
  - publish

build-10.3.0:
  image: node:10.3.0-alpine
  stage: build
  services:
    - mongo
  script:
    - npm run build

build-11.0.0:
  image: node:11.0.0-alpine
  stage: build
  services:
    - mongo
  script:
    - npm run build

build-12.0.0:
  image: node:12.0.0-alpine
  stage: build
  services:
    - mongo
  script:
    - npm run build

build-13.0.0:
  image: node:13.0.0-alpine
  stage: build
  services:
    - mongo
  script:
    - npm run build

build-14.0.0:
  image: node:14.0.0-alpine
  stage: build
  services:
    - mongo
  script:
    - npm run build

publish:
  stage: publish
  image: node:10.3.0-alpine
  script:
    - *authenticate-to-package-registry
    - cat .npmrc
    - npm ci
    - npm run make-distribution
    - export RM_TMP_TAG=cicd-$(date +%s)
    - npm publish --access public --tag $RM_TMP_TAG
    - ./tag-nodejs
  only:
    - /^\d+\.\d+\.\d+(\-[^\.]+\.\d+)?$/
