.authenticate-npm:
  - &authenticate-npm |
    echo "$NPM_SCOPE:registry=https://$NPM_REGISTRY_HOST/" >> ~/.npmrc
    echo "//$NPM_REGISTRY_HOST/:_authToken=$NPM_TOKEN" >> ~/.npmrc

before_script:
  - node --version
  - npm --version

stages:
  - build
  - publish

build-12.0.0:
  image: node:12.0.0-alpine
  stage: build
  services:
    - mongo
  script:
    - *authenticate-npm
    - npm run build

build-14.0.0:
  image: node:14.0.0-alpine
  stage: build
  services:
    - mongo
  script:
    - *authenticate-npm
    - npm run build

publish:
  stage: publish
  image: node:12-alpine
  script:
    - *authenticate-npm
    - npm ci
    - npm run make-distribution
    - npm publish --verbose --tag sha-$CI_COMMIT_SHORT_SHA
    - RM_TMP_TAG=sha-$CI_COMMIT_SHORT_SHA RM_KEEP_TMP_TAG=1 ./tag-nodejs
  only:
    - /^\d+\.\d+\.\d+(\-[^\.]+\.\d+)?$/
